# High-capacity scaling configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.scale.yml up -d

version: '3.8'

services:
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - sentinel-network

  # Additional Python containers (popular language)
  python-executor-3:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.python
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=python-3
      - LANGUAGE=python
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-network

  python-executor-4:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.python
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=python-4
      - LANGUAGE=python
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-network

  # Additional Java containers
  java-executor-3:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=java-3
      - LANGUAGE=java
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-network

  java-executor-4:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=java-4
      - LANGUAGE=java
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-network

  # Additional JavaScript containers
  javascript-executor-2:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.javascript
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=javascript-2
      - LANGUAGE=javascript
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-network

networks:
  sentinel-network:
    external: true
