version: '3.8'

services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --protected-mode no
    volumes:
      - redis_data:/data
    networks:
      - sentinel-network

  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - "8910:8910"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - sentinel-network

volumes:
  redis_data:

networks:
  sentinel-network:
    driver: bridgecpp-executor:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.cpp
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=cpp-1
      - LANGUAGE=cpp
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-networkgo-executor:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.go
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=go-1
      - LANGUAGE=go
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-networkjava-executor:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.java
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=java-1
      - LANGUAGE=java
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-networkjavascript-executor:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.javascript
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=javascript-1
      - LANGUAGE=javascript
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-networkpython-executor:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.python
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=python-1
      - LANGUAGE=python
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-networkrust-executor:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.rust
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXECUTOR_ID=rust-1
      - LANGUAGE=rust
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-network