apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-executor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-executor
  template:
    metadata:
      labels:
        app: python-executor
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: python-executor
        image: harshithd/sentinel-executor-python:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: LANGUAGE
          value: "python"
        - name: EXECUTOR_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"