apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-executor
  template:
    metadata:
      labels:
        app: cpp-executor
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: cpp-executor
        image: harshithd/sentinel-executor-cpp:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: LANGUAGE
          value: "cpp"
        - name: CONCURRENCY
          value: "1"
        - name: EXECUTOR_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"