apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javascript-executor
  template:
    metadata:
      labels:
        app: javascript-executor
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: javascript-executor
        image: maximus5479/sentinel-executor-javascript:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: LANGUAGE
          value: "javascript"
        - name: CONCURRENCY
          value: "2"
        - name: EXECUTOR_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"