apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: typescript-executor-scaler
spec:
  scaleTargetRef:
    name: typescript-executor
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 15
  triggers:
  - type: redis
    metadata:
      address: redis:6379
      listName: bull:typescript-executor:wait
      listLength: "5"