version: '3.8'

services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --protected-mode no
    volumes:
      - redis_data:/data
    networks:
      - sentinel-network

  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - "8910:8910"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - sentinel-network

volumes:
  redis_data:

networks:
  sentinel-network:
    driver: bridge